# Generated by Django 3.2.6 on 2021-08-21 19:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Napiš jméno a příjmení zaměstnance', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('prijmeni', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('description', wagtail.core.blocks.TextBlock(max_length=200, required=False)), ('phone', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('email', wagtail.core.blocks.CharBlock(max_length=60, required=False))])))]))], blank=True, null=True),
        ),
    ]
